apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: account-service 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: account-service 
    spec:
      containers:
        - name: account-service 
          image: usharegistry.azurecr.io/account-service 
          ports:
          - containerPort: 6000
---
apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: account-service 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-service 
    spec:
      containers:
        - name: auth-service 
          image: usharegistry.azurecr.io/auth-service 
          ports:
          - containerPort: 5000
---
apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: config 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: config 
    spec:
      containers:
        - name: config 
          image: usharegistry.azurecr.io/config 
          ports:
          - containerPort: 8888
---
apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: gateway 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway 
    spec:
      containers:
        - name: gateway 
          image: usharegistry.azurecr.io/gateway 
          ports:
          - containerPort: 4000
---
apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: monitoring 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: monitoring 
    spec:
      containers:
        - name: monitoring 
          image: usharegistry.azurecr.io/monitoring 
          ports:
          - containerPort: 8080
---
apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: notification-service 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: notification-service 
    spec:
      containers:
        - name: notification-service 
          image: usharegistry.azurecr.io/notification-service 
          ports:
          - containerPort: 8000
---
apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: registry 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry 
          image: usharegistry.azurecr.io/registry
          ports:
          - containerPort: 8761
---
apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: statistics-service 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: statistics-service
    spec:
      containers:
        - name: statistics-service 
          image: usharegistry.azurecr.io/statistics-service
          ports:
          - containerPort: 7000
---
apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: turbine-stream-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: turbine-stream-service
    spec:
      containers:
        - name: turbine-stream-service 
          image: usharegistry.azurecr.io/turbine-stream-service
          ports:
          - containerPort: 8989
