apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: account-service 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: account-service 
    spec:
      containers:
        - name: account-service 
          image: sqshq/piggymetrics-account-service
          ports:
          - containerPort: 6000
          env:
            - name: CONFIG_SERVICE_PASSWORD
              value: password
            - name: NOTIFICATION_SERVICE_PASSWORD
              value: password
            - name: STATISTICS_SERVICE_PASSWORD
              value: password
            - name: ACCOUNT_SERVICE_PASSWORD
              value: password
            - name: MONGODB_PASSWORD
              value: password

---
apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: auth-service 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-service 
    spec:
      containers:
        - name: auth-service 
          image: sqshq/piggymetrics-auth-service 
          ports:
          - containerPort: 5000
          env:
            - name: CONFIG_SERVICE_PASSWORD
              value: password
            - name: NOTIFICATION_SERVICE_PASSWORD
              value: password
            - name: STATISTICS_SERVICE_PASSWORD
              value: password
            - name: ACCOUNT_SERVICE_PASSWORD
              value: password
            - name: MONGODB_PASSWORD
              value: password
      
---
apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: config 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: config 
    spec:
      containers:
        - name: config 
          image: sqshq/piggymetrics-config
          ports:
          - containerPort: 8888
          env:
            - name: CONFIG_SERVICE_PASSWORD
              value: password
            - name: NOTIFICATION_SERVICE_PASSWORD
              value: password
            - name: STATISTICS_SERVICE_PASSWORD
              value: password
            - name: ACCOUNT_SERVICE_PASSWORD
              value: password
            - name: MONGODB_PASSWORD
              value: password
---
apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: gateway 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway 
    spec:
      containers:
        - name: gateway 
          image: sqshq/piggymetrics-gateway
          ports:
          - containerPort: 4000
          env:
            - name: CONFIG_SERVICE_PASSWORD
              value: password
            - name: NOTIFICATION_SERVICE_PASSWORD
              value: password
            - name: STATISTICS_SERVICE_PASSWORD
              value: password
            - name: ACCOUNT_SERVICE_PASSWORD
              value: password
            - name: MONGODB_PASSWORD
              value: password
---
apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: monitoring 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: monitoring 
    spec:
      containers:
        - name: monitoring 
          image: sqshq/piggymetrics-monitoring
          ports:
          - containerPort: 8080
          env:
            - name: CONFIG_SERVICE_PASSWORD
              value: password
            - name: NOTIFICATION_SERVICE_PASSWORD
              value: password
            - name: STATISTICS_SERVICE_PASSWORD
              value: password
            - name: ACCOUNT_SERVICE_PASSWORD
              value: password
            - name: MONGODB_PASSWORD
              value: password
---
apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: notification-service 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: notification-service 
    spec:
      containers:
        - name: notification-service 
          image: sqshq/piggymetrics-notification-service
          ports:
          - containerPort: 8000
          env:
            - name: CONFIG_SERVICE_PASSWORD
              value: password
            - name: NOTIFICATION_SERVICE_PASSWORD
              value: password
            - name: STATISTICS_SERVICE_PASSWORD
              value: password
            - name: ACCOUNT_SERVICE_PASSWORD
              value: password
            - name: MONGODB_PASSWORD
              value: password
---
apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: registry 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry 
          image: sqshq/piggymetrics-registry
          ports:
          - containerPort: 8761
          env:
            - name: CONFIG_SERVICE_PASSWORD
              value: password
            - name: NOTIFICATION_SERVICE_PASSWORD
              value: password
            - name: STATISTICS_SERVICE_PASSWORD
              value: password
            - name: ACCOUNT_SERVICE_PASSWORD
              value: password
            - name: MONGODB_PASSWORD
              value: password
---
apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: statistics-service 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: statistics-service
    spec:
      containers:
        - name: statistics-service 
          image: sqshq/piggymetrics-statistics-service
          ports:
          - containerPort: 7000
          env:
            - name: CONFIG_SERVICE_PASSWORD
              value: password
            - name: NOTIFICATION_SERVICE_PASSWORD
              value: password
            - name: STATISTICS_SERVICE_PASSWORD
              value: password
            - name: ACCOUNT_SERVICE_PASSWORD
              value: password
            - name: MONGODB_PASSWORD
              value: password
---
apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: turbine-stream-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: turbine-stream-service
    spec:
      containers:
        - name: turbine-stream-service 
          image: sqshq/piggymetrics-turbine-stream-service
          ports:
          - containerPort: 8989
          env:
            - name: CONFIG_SERVICE_PASSWORD
              value: password
            - name: NOTIFICATION_SERVICE_PASSWORD
              value: password
            - name: STATISTICS_SERVICE_PASSWORD
              value: password
            - name: ACCOUNT_SERVICE_PASSWORD
              value: password
            - name: MONGODB_PASSWORD
              value: password
---
apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: auth-mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-mongodb
    spec:
      containers:
        - name: auth-mongodb 
          image: sqshq/piggymetrics-mongodb
          ports:
          - containerPort: 80
          env:
            - name: CONFIG_SERVICE_PASSWORD
              value: password
            - name: NOTIFICATION_SERVICE_PASSWORD
              value: password
            - name: STATISTICS_SERVICE_PASSWORD
              value: password
            - name: ACCOUNT_SERVICE_PASSWORD
              value: password
            - name: MONGODB_PASSWORD
              value: password
---
apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: account-mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: account-mongodb
    spec:
      containers:
        - name: account-mongodb
          image: sqshq/piggymetrics-mongodb
          ports:
          - containerPort: 80
          env:
            - name: CONFIG_SERVICE_PASSWORD
              value: password
            - name: NOTIFICATION_SERVICE_PASSWORD
              value: password
            - name: STATISTICS_SERVICE_PASSWORD
              value: password
            - name: ACCOUNT_SERVICE_PASSWORD
              value: password
            - name: MONGODB_PASSWORD
              value: password
---
apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: notification-mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: notification-mongodb
    spec:
      containers:
        - name: notification-mongodb
          image: sqshq/piggymetrics-mongodb
          ports:
          - containerPort: 80
          env:
            - name: CONFIG_SERVICE_PASSWORD
              value: password
            - name: NOTIFICATION_SERVICE_PASSWORD
              value: password
            - name: STATISTICS_SERVICE_PASSWORD
              value: password
            - name: ACCOUNT_SERVICE_PASSWORD
              value: password
            - name: MONGODB_PASSWORD
              value: password
          
      
