apiVersion: v1
kind: Service
metadata:
    name: rabbitmq
spec:
    ports:
    - port: 15672 
    selector:
        app: rabbitmq
---

apiVersion: v1
kind: Service
metadata:
    name: account-service
spec:
    ports:
    - port: 6000 
    selector:
        app: account-service
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  ports:
  - port: 5000
  selector:
    app: auth-service
---
apiVersion: v1
kind: Service
metadata:
  name: config 
spec:
  ports:
  - port: 8888
  selector:
    app: config 
---
apiVersion: v1
kind: Service
metadata:
  name: gateway  
spec:
  type: LoadBalancer
  ports:
  - port: 4000
  selector:
    app: gateway
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring  
spec:
  ports:
  - port: 8080
  selector:
    app: monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service  
spec:
  ports:
  - port: 8000
  selector:
    app: notification-service
---
apiVersion: v1
kind: Service
metadata:
  name: registry  
spec:
  ports:
  - port: 8761
  selector:
    app: registry
---
apiVersion: v1
kind: Service
metadata:
  name: statistics-service  
spec:
  ports:
  - port: 7000
  selector:
    app: statistics-service
---
apiVersion: v1
kind: Service
metadata:
  name: turbine-stream-service  
spec:
  ports:
  - port: 8989
  selector:
    app: turbine-stream-service
---
apiVersion: v1
kind: Service
metadata:
  name: notification-mongodb
spec:
  ports:
  - port: 80
  selector:
    app: notification-mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: account-mongodb
spec:
  ports:
  - port: 80
  selector:
    app: account-mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: account-mongodb
spec:
  ports:
  - port: 80
  selector:
    app: account-mongodb
